format = """
$directory\
$git_branch\
$git_status\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
$docker_context\
bca9e1\
$character\
"""

[character]
success_symbol = "[](bold #bb9af7)"
error_symbol = ""

[username]
show_always = true
format = '[$user ]($style)'
disabled = false

[hostname]
format = '[$hostname](#a0a9cb ) in(#a0a9cb ) '
disabled = false

[directory]
format = "[ $path ]($style)"
truncation_length = 0
truncation_symbol = "~/"

[c]
symbol = " "
format = '[ $symbol ($version) ]($style)'

[cpp]
symbol = " "
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
format = '[ $symbol $context ]($style)'

[elixir]
symbol = " "
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
format = '[ $symbol $branch ]($style)'

[git_status]
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
format = '[ $symbol ($version) ]($style)'

[gradle]
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
format = '[ $symbol ($version) ]($style)'
